begin js
Metelkov/003_frontend_cafe_figma_template pull request #4
Opened 2020-10-05 17:00 UTC by Metelkov

2020-11-10 22:52 UTC, avdeev commented on index_maga.html
> +      <div class = "start__opening__hours">
у элемента не может быть элемент

правильнее будет `start__opening-hours`

2020-11-10 22:53 UTC, avdeev requested changes
есть ошибки в БЭМ

у элемента не может быть элемента

2020-11-11 15:51 UTC, avdeev requested changes

2020-11-11 15:51 UTC, avdeev commented on gallery_change.js
> +let end__part_pic = ".jpg)";
предпочитай `const`, вместо `let`

2020-11-11 15:51 UTC, avdeev commented on gallery_change.js
> +let first__part__pic = "no-repeat center url(event_bottom_0";
переменные в JS называем не по БЭМ :)

правильнее будет `firstPartPicture`

2020-11-12 09:11 UTC, Metelkov commented on gallery_change.js
> +let end__part_pic = ".jpg)";
раньше было var, потом поменяли на let, а const это константой считается и по идеологии не должна изменять значение

2020-11-12 09:12 UTC, Metelkov commented on gallery_change.js
> +let first__part__pic = "no-repeat center url(event_bottom_0";
да, у меня как раз был вопрос по названию переменных
можно в этом проекте я не буду их переписывать, а в новом учту все свои кривописания

2020-11-12 13:05 UTC, avdeev commented on gallery_change.js
> +let first__part__pic = "no-repeat center url(event_bottom_0";
да, без проблем

вот хорошая статья

https://learn.javascript.ru/variable-names

2020-11-12 13:06 UTC, avdeev commented on gallery_change.js
> +let end__part_pic = ".jpg)";
так она и не меняется нигде после создания

разве нет?

2020-11-13 13:06 UTC, Metelkov commented on gallery_change.js
> +let end__part_pic = ".jpg)";
вчера залил исправленное

2020-11-13 15:43 UTC, avdeev approved these changes

2020-11-14 17:44 UTC, merged